// AppReducer
export const LOADING = 'APP/LOADING'
export const UN_LOADING = 'APP/UN_LOADING'
export const ERROR = 'APP/ERROR'
export const UN_ERROR = 'APP/UN_ERROR'
export const SUCCESS = 'APP/SUCCESS'
export const UN_SUCCESS = 'APP/UN_SUCCESS'
export const FULLSCREEN = 'APP/FULLSCREEN'
export const SET_USER = 'APP/SET_USER'
export const SET_MAIN_MENU = 'APP/SET_MAIN_MENU'
export const SET_TOKEN_TIMER = 'APP/SET_TOKEN_TIMER'

//JournalReducer
export const SET_SECTORS = 'JOURNAL/SET_SECTORS'
export const SET_ORDERS_SECTOR = 'JOURNAL/SET_ORDERS_SECTOR'
export const SET_TODAY_ORDERS = 'JOURNAL/SET_TODAY_ORDERS'
export const SET_OVERDUE_ORDERS = 'JOURNAL/SET_OVERDUE_ORDERS'
export const SET_FUTURE_ORDERS = 'JOURNAL/SET_FUTURE_ORDERS'
export const REMOVE_ORDERS = 'JOURNAL/REMOVE_ORDERS'
export const SET_COMMENTS_ORDER = 'JOURNAL/SET_COMMENTS_ORDER'
export const REMOVE_COMMENTS_ORDER = 'JOURNAL/REMOVE_COMMENTS_ORDER'

//ConstructorReducer
export const SET_TEST = "CONSTRUCTOR/SET_TEST"